3d: False

encoder:
  arch: vgg

  vgg:
    layer: 3
    pool: max
    
decoder:
  arch: vgg

  vgg:
    layer: 3
    in_dim: 256
    up: bilinear
    pretrained: False

discriminator:
  spectral_norm: true

loss:
  render:
    terms: [pixel, content, distill]
    weights: [1, 1, 0]

    pixel:
      loss_type: l1

    content:
      loss_type: l1
      layers: !!python/list [3]
      norm: null

    distill:
      loss_type: l1
      layers: !!python/list [3]
      norm: null

  ganD: hinge
  ganG: hinge

  weights: !!python/list [1, 0, 0]

data:
  name: coco
  im_size: 256

train:
  batch_size: 8
  n_itrs: 50000

  optim: adam
  lr: 1.e-4
  beta1: 0.9
  beta2: 0.999
  decay_itrs: !!python/list [-1]
  decay: 0.5