3d: true

encoder:
  arch: pcd

  pcd:
    n_levels: 3

    aggregate: max
    norm: batch
    actv: relu
    res: true

    in_conv: mr
    in_dim: 64
    in_radius: 0.015
    in_k: 16

    block: mr
    scale_factor: !!python/list [4, 4, 4]
    dims: !!python/list [128, 256, 512]
    depth: !!python/list [1, 2, 1]
    radius: !!python/list [[[0.015, 0.025]], [[0.025, 0.05], [0.05, 0.05]], [[0.05, 0.1]]]
    k: !!python/list [[[16, 16]], [[16, 16], [16, 16]], [[16, 16]]]

    out_fc: true
    out_relu: true
    up: linear
    
decoder:
  arch: pcd

  pcd:
    n_levels: 3

    aggregate: max
    norm: batch
    actv: relu
    res: true

    in_dim: 512

    block: mr
    dims: !!python/list [256, 128, 64]
    depth: !!python/list [1, 2, 1]
    radius: !!python/list [[[0.1, 0.05]], [[0.05, 0.05], [0.05, 0.025]], [[0.025, 0.015]]]
    k: !!python/list [[[16, 16]], [[16, 16], [16, 16]], [[16, 16]]]
    up: linear

    out_norm: false

discriminator:
  spectral_norm: true

loss:
  render:
    terms: [pixel, content, distill]
    weights: [1, 1, 10]

    pixel:
      loss_type: l1

    content:
      loss_type: l1
      layers: !!python/list [4]
      norm: null

    distill:
      loss_type: l1
      layer: 4
      norm: null

  ganD: hinge
  ganG: hinge

  weights: !!python/list [1, 0, 0]

data:
  name: pcd
  n_target_views: 1
  x_lim: !!python/list [-0.05, 0.05]
  y_lim: !!python/list [-0.05, 0.05]
  z_lim: !!python/list [-0.05, 0.15]

train:
  batch_size: 8
  n_itrs: 50000

  h: 224
  w: 224
  pcd_size: 262144

  optim: adam
  lr: 1.e-4
  beta1: 0.9
  beta2: 0.999
  decay_itrs: !!python/list [-1]
  decay: 0.5
